dist: trusty
sudo: required

language: php

php:
  - 7.0

jdk:
  - oraclejdk8

addons:
  sonarqube:
    organization: "adlerosn-github"
    token: $SONAR_TOKEN

script:
  - php -l *.php
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
