dist: trusty
sudo: required

language: php

php:
  - 7.0

jdk:
  - oraclejdk8

addons:
  sonarqube:
    token: $SONAR_TOKEN

script:
  - php -l *.php
  - echo "Will not run: sonar-scanner -X"


cache:
  directories:
    - '$HOME/.sonar/cache'
